name: python-workshop
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - pandas
  - cartopy
  - h5netcdf
  - netcdf4
  - pydap
  - pyproj
  - eccodes
  - cython
  - pygrib
  - s3fs
  - scipy
  - xarray
